modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/abigailfails/HelpfulHitboxes/issues"
license = "https://github.com/abigailfails/HelpfulHitboxes/blob/main/LICENSE"

[[mods]]
modId = "helpfulhitboxes"
version = "${version}"
displayName = "Helpful Hitboxes"
authors = "abigailfails"
logoFile = "assets/helpfulhitboxes/icon.png"
description = '''
Makes the visual hitbox of certain small blocks larger when you're holding a block of that type, to help with building.
'''

[[dependencies.helpfulhitboxes]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.helpfulhitboxes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"