modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/abigailfails/Modicum/issues" #optional
license="https://github.com/abigailfails/Modicum/blob/master/LICENSE.txt"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="helpfulhitboxes"
version="${file.jarVersion}"
displayName="Helpful Hitboxes"
#displayURL="http://example.com/" #optional
logoFile="modicum.png"
credits="Zymyttymyz for the mod idea"
authors="abigailfails"
description='''
Makes the hitbox of certain small blocks larger under specific circumstances, to help with building.
'''
[[dependencies.modicum]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modicum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"